### PR TITLE
DeepEM Notebook

### PR DESCRIPTION
**Pull request by PaulJWright**
Here is the DeepEM notebook. I have added it as Chapter 4.

### CODE REVIEW

**Comment by PaulJWright** [comment]
I have just fixed some typos and added an acknowledgement to the end of the notebook. It should now be ready to go! Thanks again.

**Comment by PaulJWright** [comment]
I was made aware of a mistake in one of the labels on the main gif. Corrected and ready to go!

**Comment by mbobra** [comment]
Sweet, thanks @PaulJWright !!! 🎉I'll integrate and it will probably take ~20 minutes for pages to deploy.

**Comment by mbobra** [comment]
Interesting, github has identified three security vulnerabilities:

> Known **moderate severity** security vulnerability detected in jekyll >= 3.7.0, < 3.7.4 defined in Gemfile.lock. Gemfile.lock update suggested: jekyll ~> 3.7.4.

> Known **moderate severity** security vulnerability detected in ffi < 1.9.24 defined in Gemfile.lock.
> Gemfile.lock update suggested: ffi ~> 1.9.24.

> Known  **moderate severity** security vulnerability detected in rubyzip <= 1.2.1 defined in Gemfile.lock. Gemfile.lock update suggested: rubyzip ~> 1.2.2.

@PaulJWright: Are these easy to modify or do they require a lot of work?

**Comment by PaulJWright** [comment]
I am not sure what would be causing this. I will investigate.

**Comment by PaulJWright** [comment]
the Gemfile.lock is in the main directory, and I assume these issues are to do with making web pages from the markdown/notebook files? I am not sure it's related to the files I added.

**Comment by mbobra** [comment]
Truth. Sorry for bugging you about the gemfile. Your notebook has been [integrated](https://helioml.github.io/HelioML/chapters/04/Differential_Emission_Measurements) and it looks super awesome. Thank you, genuinely, for all your effort -- I know it takes a lot of time to beautify everything. I really appreciate it 👏

**Comment by PaulJWright** [comment]
Thank you! No worries, I was interested in what was causing it anyway!

**Comment by PaulJWright** [comment]
One last thing. On the notebook, the figures seem to be missing (broken images), but they are present if I interact with the notebook!

**Comment by mbobra** [comment]
Yeah I noticed this too, I think this is a problem on our end. So you are off the hook.

@jmason86 do you know the cause? I have seen it elsewhere too.

**Comment by PaulJWright** [comment]
You've probably noticed already, but I see that the image files are needed here: https://github.com/PaulJWright/HelioML/tree/master/images/chapters and @jmason86 seemed to have to manually add them? I can do a pull request to give you the files?

**Comment by mbobra** [comment]
You are right! It looks right on my end now, does it look okay to you?

**Comment by PaulJWright** [comment]
Looks good! Thanks again, i'm glad it's all sorted.

**Comment by jmason86** [comment]
Thanks for the contribution!

**Pull request merged**
