### PR TITLE
built html for chapter 9

### PR DESCRIPTION
**Pull request by mbobra**
This required modifying `_data/toc.yml`, which wasn't modified in PR #65

### CODE REVIEW

**Comment by mbobra** [comment]
@jmason86 It looks like I am having some issues rendering plotly in the jupyter-book. It looks like [there is a workaround](https://github.com/executablebooks/jupyter-book/issues/93), so I can try this. Another issue is that this notebook uses shell commands like `wget` which aren't necessarily installed for everyone (for example, I get the error: `/bin/bash: wget: command not found`). Suggestions?

**Comment by jmason86** [comment]
Nice find on the work around, definitely worth a try. For wget, maybe we just ask the author to switch from a shell command to a python command. There's a [python implementation of wget here](https://pypi.org/project/wget/) that maybe would do it with almost no syntax change?

**Comment by raplima** [comment]
I can update the notebook if that helps! Would any of [these](https://gist.github.com/raplima/af275a481de1dcca2adb7b26d47b08f5) be better than shell's `wget`?

**Comment by raplima** [comment]
I was thinking maybe you'd prefer to update `unzip` to a python command as well?
```python
from zipfile import ZipFile
with ZipFile('example.zip', 'r') as zfile:
   zfile.extractall()
```

**Comment by mbobra** [comment]
@raplima If you don't mind, we would definitely appreciate updating the notebook to use only Python. The idea is that someone can just pip install all the packages listed in your import statement and run the notebook. 

Also, do you mind saving the plotly files to html, adding the html files to your chapter, and loading the html files in your notebook? I think that solution may allow the plotly-generated files to render in the jupyter-book. Sorry about this workround. You can write a sentence above the code-block about how this is a workaround in order for plotly to render properly in jupyter-book.

**Comment by raplima** [comment]
@mbobra I will look into these

**Comment by jmason86** [comment]
One additional alternative to test with the plotly plots would be to host them on Chart Studio and include the HTML embed link. We could make a dedicated account to be sure it'd be there in perpetuity.

**Pull request merged**
