### PR TITLE
Added forecasting relativist electrons chapter

### PR DESCRIPTION
**Pull request by raplima**
I added the chapter based on [Forecasting Megaelectron‐Volt Electrons Inside Earth's Outer Radiation Belt: PreMevE 2.0 Based on Supervised Machine Learning Algorithms](https://doi.org/10.1029/2019SW002399). The chapter content was incorporated as chapter 8.

### CODE REVIEW

**Comment by mbobra** [comment]
Thank you so much for your PR, @raplima! We will review and merge sometime in the next couple weeks.

**Comment by raplima** [comment]
@mbobra , thank you very much for all the help! I hope it goes smoothly.

**Comment by jmason86** [comment]
Initial review looks good! 

@raplima Couple of action items for you if you're willing: 

- [ ] Create a content/09/ folder and move your contents there and remove your content/08 folder. We have another chapter PR coming in just before this one taking the 08 slot and want to avoid file conflicts. 
- [ ] Update content/table_of_contents.md for your new chapter 9, following the example of the other chapters
- [ ] Update the root/environment.yml file, specifying any package dependencies specific to your code, including version number (we didn't think of this until recently so we're now having to go back and figure out what versions thing need to run for the older chapters, which is, let me tell you, not a lot of fun. Much easier to do it upon initial commit.

**Comment by jmason86** [comment]
@mbobra The notebook in this chapter initially refused to render on github but it worked after a couple tries. Also worked with nbviewer. 

Also, we should decide what we want to do about data inclusion (even if file sizes are small). This notebook is really nice in that it already includes the code to download the data fresh via wget. But the commit also includes the data files (.txt). They aren't necessary to run the code and being small and simple, it's kind of nice to have them there for quick viewing. But that won't be the case for bigger data sets. Just something we should think about.

**Comment by jmason86** [comment]
Notebook review: 

* Great overall! 
* I really like the links to more information (e.g.,`melt` and `plotly`, MinMax scaling) 
* Also liked that you wrote out equations so that they render nicely
* Really liked the introductory text for each section, particularly section 3 and 4
* Nice summaries, like just above In [42] "As a recap, ..." and all of section 5

- [ ] The plotly plot doesn't render in nbviewer. It might once we process for display in the book proper. But if not, we should see if we can provide a link to the ChartStudio -- that generally plays nice with HTML embedding. That way readers can interact without needing to run the code -- that'd actually be amazing. We'll have to wait until after merge and made live to check if further action is needed. 
- [ ] Typo just above In [31]: "into three different dataframes acconding" should be "according" (wow.. can't believe I spotted that)
- [ ] Figure for In [36] and In [43] not showing up either (same as the previous plotly action)
- [ ] If it's easy, can you state either at the beginning or the end how much wall-clock time it takes for you to run this entire notebook, and also how long it takes to run through the expanded version of the paper? Plus whether this was run on a desktop/laptop or cluster. I think this is just of general interest to some readers. 

That's it from me on the notebook! Looks so good!

**Comment by raplima** [comment]
@jmason86 Thank you very much for the review! 

> Update the root/environment.yml file, specifying any package dependencies specific to your code, including version number (we didn't think of this until recently so we're now having to go back and figure out what versions thing need to run for the older chapters, which is, let me tell you, not a lot of fun. Much easier to do it upon initial commit.

Yea, that seems no fun to track all versions. I added the new packages into environment.yml (I later noticed I forgo to commit and push the files outside my original content/08 folder, I hope I got them all now). But I was unsure if I should add version numbers to packages already listed, so I added the version number only to the "new ones":
```
    - plotly == 4.4.1
    - tensorflow == 2.3.0
```
But I added a cell at the end of the notebook ([48]) to print the version numbers for all libraries used:
```
Library              version
numpy                1.18.5
pandas               1.0.5
matplotlib           3.2.2
seaborn              0.10.1
plotly               4.4.1
scikit-learn         0.22.2.post1
tensorflow           2.3.0
```
I also added a cell ([47]) to answer:

> If it's easy, can you state either at the beginning or the end how much wall-clock time it takes for you to run this entire notebook, and also how long it takes to run through the expanded version of the paper? Plus whether this was run on a desktop/laptop or cluster. I think this is just of general interest to some readers.

But I actually never properly measured how long it takes to run through the expanded version. I recall something around 3 hours, which I included in the notebook as a comment. 

> Typo just above In [31]: "into three different dataframes acconding" should be "according" (wow.. can't believe I spotted that)

Great catch! Thank you. 

Regarding missing plots, I think maybe plotly plots won't render on github unless they're image files rather than html (e.g., [here](https://github.com/plotly/plotly.py/issues/931#issuecomment-417642992) and [here](https://github.com/nicolaskruchten/plotly_img_test/blob/master/Untitled.ipynb)). I am not very familiar with nbviewer and ChartStudio, but I'm hoping the merge helps too. 

The updated list:

- [x]  Create a content/09/ folder and move your contents there and remove your content/08 folder. We have another chapter PR coming in just before this one taking the 08 slot and want to avoid file conflicts.
- [x]  Update content/table_of_contents.md for your new chapter 9, following the example of the other chapters
- [x]  Update the root/environment.yml file, specifying any package dependencies specific to your code, including version number (we didn't think of this until recently so we're now having to go back and figure out what versions thing need to run for the older chapters, which is, let me tell you, not a lot of fun. Much easier to do it upon initial commit.
- [ ]  The plotly plot doesn't render in nbviewer. It might once we process for display in the book proper. But if not, we should see if we can provide a link to the ChartStudio -- that generally plays nice with HTML embedding. That way readers can interact without needing to run the code -- that'd actually be amazing. We'll have to wait until after merge and made live to check if further action is needed.
- [x]  Typo just above In [31]: "into three different dataframes acconding" should be "according" (wow.. can't believe I spotted that)
- [ ]  Figure for In [36] and In [43] not showing up either (same as the previous plotly action)
- [x]  If it's easy, can you state either at the beginning or the end how much wall-clock time it takes for you to run this entire notebook, and also how long it takes to run through the expanded version of the paper? Plus whether this was run on a desktop/laptop or cluster. I think this is just of general interest to some readers.

**Comment by jmason86** [comment]
Awesome! That's it from me then. Will wait for @mbobra to give it a once over before we merge and then we can check if the plots render in the online book (🤞).

**Comment by raplima** [comment]
Cool! Thank you very much for the help!

**Comment by jmason86** [comment]
Alright, we're nearly ready to merge! We had another chapter come in at the same time. Can you pull, deconflict on the 3 files listed above, and commit?

**Comment by mbobra** [comment]
> Alright, we're nearly ready to merge! We had another chapter come in at the same time. Can you pull, deconflict on the 3 files listed below, and commit?

@jmason86 I pulled the changes and resolved the conflicts. Can you approve?

**Review by jmason86 — APPROVED** [review]

**Comment by raplima** [comment]
@mbobra and @jmason86, thank you very much for setting it all up!

**Pull request merged**
